# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: 1168fabf
    url: /#resume-biography-3
    weight: 10
  - name: Blog
    identifier: 461ef24f
    url: /blog/
    weight: 20
  - name: Contact
    identifier: contact
    url: /#contact
    weight: 30
  - name: Contributions
    identifier: projects
    url: /projects/
    weight: 40
