hugoblox:
  schema: "2.0"
  identity:
    name: John Martin Fredriksen
    type: person
    tagline: Clinical Dietitian
    description: John Martin Fredriksen, RD, MS
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: full
    spacing: spacious
    avatar_shape: circle
  header:
    enable: true
    style: navbar-simple
    sticky: true
    align: right
    search: true
    theme_toggle: true
    language_switcher: false
  footer:
    style: minimal
    language_switcher: false
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
    citations:
      style: chicago
  search:
    enable: true
  locale: {}
  privacy:
    enable: false
